### ISSUE TITLE
[Request] Integrated RTP Command

### ISSUE THREAD

**Issue by UPSOKen** [DeathGOD7/unexpectedspawn-paper#20] opened 2023-10-08 14:55 UTC
It would be nice if the plugin had a built in RTP command. Something like: **/unexpectspawn rtp <xmin> <xmax> <ymin> <ymax> <world> [player]**

A few important features of this command:

- Should be executable as console (Allowing for use in things like GUI item menus).
- Should allow you to define the specific min/max and world for the RTP.
- Should let you define the player to execute the RTP on (But should execute to self, if no player is defined).
- Should implement the spawn-block-blacklist safety check from the global config.
- Should implement the fail radius from the global config.
- If the command has an alias (Ex. **/rtp**) - that alias should be configurable within the config.

I think this command would be a good complimentary feature, while taking advantage of some already implemented features.

**Comment by RexSE7EN** [comment] 2023-10-12 11:22
Added your features. Please try the snapshot build from [actions](https://github.com/DeathGOD7/unexpectedspawn-paper/actions).
Changelog : https://github.com/DeathGOD7/unexpectedspawn-paper/compare/74e6153...268a7de

**Comment by UPSOKen** [comment] 2023-10-12 13:41
Works great so far in testing. Will put it into production server this evening to do some public testing.

**Comment by RexSE7EN** [comment] 2023-10-12 14:09
> Works great so far in testing. Will put it into production server this evening to do some public testing.

Also quick note, blacklisted worlds don't apply in command rtp as it's like force teleport. So if you don't specify the world argument and run the command as a player in the nether world/through console by specifying player that is in the nether world, it will tp to bedrock. It is not a bug (if you want the blacklist world to apply on command too, it can be added).

Cheers and have a nice day.

**Comment by RexSE7EN** [comment] 2023-10-12 14:12
Once it's fully tested I would release it with some minor fixes.

**Comment by UPSOKen** [comment] 2023-10-12 14:12
> > Works great so far in testing. Will put it into production server this evening to do some public testing.
> 
> Also quick note, blacklisted worlds don't apply in command rtp as it's like force teleport. So if you don't specify the world argument and run the command as a player in the nether world/through console by specifying player that is in the nether world, it will tp to bedrock. It is not a bug (if you want the blacklist world to apply on command too, it can be added).
> 
> Cheers and have a nice day.

I think that makes sense. You should be able to bypass the blacklist via the command.

But, I do wish there was some way to make it useful in the nether, because I would use it there, but it appears to just put people on bedrock.

This is not an issue for me, as I have an anti-nether roof that will TP them below it, but still something you may want to add for other folks.

Either way, for my use-case - this update should work perfectly!

**Comment by RexSE7EN** [comment] 2023-10-12 23:58
Done. Random TP works in the nether too. Works for both the respawn/join event and the rtp command.

*(I don't know why people would want to randomize spawn in nether while respawning after dying just to be stuck, but there is a way if needed)*

**Comment by RexSE7EN** [comment] 2023-10-12 23:59
Please try the latest snapshot build from [actions](https://github.com/DeathGOD7/unexpectedspawn-paper/actions).

**Comment by RexSE7EN** [comment] 2023-10-13 21:55
The new version is out (v1.0.0) and can be used in production. I will be closing this issue as it's solved. If you think this issue still needs attention, please re-open it.

**Closed as completed by RexSE7EN** 2023-10-13 21:55 UTC
Labels: enhancement, solved, priority: low, status: approved
