### ISSUE TITLE
A error

### ISSUE THREAD

**Issue by haha44444** [DeathGOD7/unexpectedspawn-paper#12] opened 2021-08-18 16:26 UTC
![image](https://user-images.githubusercontent.com/60396495/129934746-b6aa73b2-721d-496c-8902-f848728f62c6.png)
There was a small mistake.

**Comment by Roshanxy** [comment] 2021-08-18 23:42
To me it looks like you’re not using paper but I could be wrong

**Comment by Shivelight** [comment] 2021-08-19 03:20
Confirmed, `adventure` is not yet available on Spigot and Paper <1.16.5 https://docs.adventure.kyori.net/platform/native.html.

@DeathGOD7 To support as many versions as possible, we can't rely on native support, instead, we use platform implementation here https://docs.adventure.kyori.net/platform/bukkit.html

**Comment by RexSE7EN** [comment] 2021-08-20 09:25
> Confirmed, `adventure` is not yet available on Spigot and Paper <1.16.5 https://docs.adventure.kyori.net/platform/native.html.
> 
> @DeathGOD7 To support as many versions as possible, we can't rely on native support, instead, we use platform implementation here https://docs.adventure.kyori.net/platform/bukkit.html

I will look into it.

**Comment by RexSE7EN** [comment] 2021-08-20 09:33
Please use the old version (0.2.1) if you are using the old version below 1.16.
We will fix it soon.

**Comment by Shivelight** [comment] 2021-08-20 09:53
> Please use the old version (0.2.1) if you are using the old version below 1.16.
> We will fix it soon.

In the meantime, I assigned myself to create an independent release hotfix until resolved.

**Comment by Shivelight** [comment] 2021-08-20 10:24
@haha44444 Please try this release https://github.com/Shivelight/unexpectedspawn-paper/releases/tag/0.3.0%2Bhotfix.1

**Comment by haha44444** [comment] 2021-08-20 13:03
> @haha44444 Please try this release https://github.com/Shivelight/unexpectedspawn-paper/releases/tag/0.3.0%2Bhotfix.1

![image](https://user-images.githubusercontent.com/60396495/130237305-eb068f19-854e-4567-8f89-2febfdad6fad.png)
There are no errors and can be loaded normally.

**Comment by RexSE7EN** [comment] 2021-08-21 10:26
As it seems it's resolved for now. Will update the plugin to support all versions of Minecraft in 0.3.1 (with new features suggested).
But for now please use the above version given by @Shivelight if you are using the paper version below 1.16.5.

Closing this issue. If you think this issue isn't solved, please re-open this issue.

**Closed as completed by RexSE7EN** 2021-08-21 10:26 UTC
Labels: solved
